### ISSUE TITLE
GetCandlesticks fix to get additional data when data is not enough

### ISSUE THREAD

**Issue by suotas** [suotas/chihuahua#9]
# overview
GetCandlesticks fix to get additional data when data is not enough.

# goal
When execute GetCandlesticks get enough datas always.

# body
get data in loop with use adjusted parameter when not enough datas

# tasks
- [ ] Exporting input parameters to an external configuration file
- [ ] Calculate parameters from current time and date
- [ ] Subtract parameters and get additional historical data if there is not enough data
